Class test.test1 Extends %Persistent
{

Storage Default
{
<Data name="test1DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^test.test1D</DataLocation>
<DefaultData>test1DefaultData</DefaultData>
<IdLocation>^test.test1D</IdLocation>
<IndexLocation>^test.test1I</IndexLocation>
<StreamLocation>^test.test1S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
